name: run test
on:
    # Runs on pushes targeting the default branch
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: environment-${{ github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # Check if pull request does not have label "not-selfcontained-ok"
    if: "!contains(github.event.pull_request.labels.*.name, 'not-selfcontained-ok')"
    steps:
    - uses: actions/checkout@v3
      with:
        # Needed to rebase against the base branch
        fetch-depth: 0
        # Checkout pull request HEAD commit instead of merge commit
        ref: ${{ github.event.pull_request.head.sha }}
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - run: npm install
    - name: Build
      run: npm run docs:build
    - name: Install dependencies
      run: |
          pip install -U leptonai && lep login
          cd web && npm install && npm run build
